### ISSUE TITLE
Support for `sass-mq` breakpoints names

### ISSUE THREAD

**Issue by vasartam** [vasartam/sass-interpolate#2]
When working with site's adaptivity, the library such as [sass-mq](https://github.com/sass-mq/sass-mq) helps a lot. It turns the usual `@media` syntax into a much more readable format:
```scss
.foo {
  @include mq($from: mobile, $until: tablet) {
    background: red;
  }
}
```
It also eliminates the need to keep in mind the exact values of your breakpoints.

However, when using `interpolate` mixin side-by-side with `mq`, this need is not eliminated. It would benefit the readability much more if you would use simple `@media` rules instead of `mq` inclusion, possibly. Take this example:

```scss
.foo {
  @include mq($from: mobile, $until: desktop) {
    background: red;
  }

  @include linear-interpolation(1440px 375px, (
    font-size: 32px 24px,
    line-height: 52px 34px
  ));
}
```

And this one:

```scss
.foo {
  @media (min-width: 375px) and (max-width: 1440px) {
    background: red;
  }

  @include linear-interpolation(1440px 375px, (
    font-size: 32px 24px,
    line-height: 52px 34px
  ));
}
```

Looks a bit better.

But it would look much better if you could write something like that instead:

```scss
.foo {
  @include mq($from: mobile, $until: desktop) {
    background: red;
  }

  @include interpolate(desktop mobile, (
    font-size: 32px 24px,
    line-height: 52px 34px
  ));
}
```

Need to teach the mixin to accept the described format inside `$screen-widths-list` parameter.

I know you can use variables for that, but it would be much more nice to have such a deep integration with `sass-mq`.
